-record(users, {id, name, password, display}).
-record(wtts, {id, wanters = ordsets:new(), havers = ordsets:new()}).
-record(auto_increment, {table, key}).
-record(cards, {id, name}).
-record(events, {time, event}).
-record(login_event, {user}).
-record(register_event, {user}).
-record(wtt_event, {user, card, kind}).
